trigger:
- main

pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - script: python verify_content.py
    displayName: 'Vérifier le contenu du fichier'

  - script: echo "##vso[task.setvariable variable=content]$(cat sample_file.json | jq -r .content)"
    displayName: 'Définir la variable content'

  - task: PublishPipelineArtifact@1
    condition: eq(variables['content'], 'true')
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifact: 'my-artifact'
